"use client"
import React, { useState } from 'react';

const REGIONS_BY_STATE: Record<string, string[]> = {
  VIC: [
    "Alexandra",
    "Aireys Inlet",
    "Fairhaven",
    "Allansford",
    "Anglesea",
    "Apollo Bay",
    "Ararat",
    "Avenel",
    "Avoca",
    "Bacchus Marsh",
    "Bairnsdale",
    "Ballan",
    "Ballarat",
    "Balnarring Beach",
    "Merricks",
    "Bannockburn",
    "Barnawartha",
    "Beaconsfield Upper",
    "Beaufort",
    "Beeac",
    "Beechworth",
    "Bellbridge",
    "Benalla",
    "Bendigo",
    "Beulah",
    "Birchip",
    "Birregurra",
    "Blackwood",
    "Boolarra",
    "Boort",
    "Briagolong",
    "Bridgewater",
    "Bright",
    "Broadford",
    "Bruthen",
    "Bulla",
    "Buninyong",
    "Bunyip",
    "Campbells Creek",
    "Camperdown",
    "Cann River",
    "Cape Paterson",
    "Cardigan Village",
    "Carisbrook",
    "Carrum Downs",
    "Casterton",
    "Castlemaine",
    "Charlton",
    "Chewton",
    "Chiltern",
    "Churchill",
    "Clifton Springs",
    "Clunes",
    "Cobden",
    "Cobram",
    "Cockatoo",
    "Cohuna",
    "Colac",
    "Coldstream",
    "Coleraine",
    "Coongulla",
    "Corinella",
    "Coronet Bay",
    "Corryong",
    "Cowes",
    "Craigieburn",
    "Cranbourne",
    "Cranbourne South",
    "Creswick",
    "Crib Point",
    "Darnum",
    "Dartmoor",
    "Daylesford",
    "Derrinallum",
    "Diggers Rest",
    "Dimboola",
    "Dinner Plain",
    "Donald",
    "Dookie",
    "Drouin",
    "Drysdale",
    "Dunkeld",
    "Dunolly",
    "Echuca",
    "Edenhope",
    "Eildon",
    "Elmore",
    "Emerald",
    "Euroa",
    "Flinders",
    "Foster",
    "Garfield",
    "Geelong",
    "Gembrook",
    "Girgarre",
    "Gisborne",
    "Glenrowan",
    "Goornong",
    "Gordon",
    "Goroke",
    "Grantville",
    "Gunbower",
    "Halls Gap",
    "Hamilton",
    "Harcourt",
    "Hastings",
    "Healesville",
    "Heathcote",
    "Heyfield",
    "Heywood",
    "Hopetoun",
    "Horsham",
    "Huntly",
    "Hurstbridge",
    "Indented Head",
    "Inglewood",
    "Inverleigh",
    "Inverloch",
    "Irymple",
    "Jeparit",
    "Kaniva",
    "Katamatite",
    "Kerang",
    "Kilmore",
    "Kinglake",
    "Koo Wee Rup",
    "Koondrook",
    "Koroit",
    "Korong Vale",
    "Korumburra",
    "Kyabram",
    "Kyneton",
    "Lake Boga",
    "Lake Bolac",
    "Lake Tyers",
    "Lakes Entrance",
    "Lancefield",
    "Lang Lang",
    "Lara",
    "Launching Place",
    "Learmonth",
    "Leitchville",
    "Leongatha",
    "Leopold",
    "Lethbridge",
    "Lindenow",
    "Linton",
    "Lismore",
    "Loch",
    "Loch Sport",
    "Lockington",
    "Longwarry",
    "Macarthur",
    "Macedon",
    "Maffra",
    "Maldon",
    "Mallacoota",
    "Malmsbury",
    "Manangatang",
    "Mansfield",
    "Marlo",
    "Maryborough",
    "Marysville",
    "Meeniyan",
    "Melbourne",
    "Melton",
    "Merbein",
    "Meredith",
    "Merino",
    "Mernda",
    "Merrigum",
    "Metung",
    "Mildura",
    "Millgrove",
    "Miners Rest",
    "Minyip",
    "Mirboo North",
    "Moe",
    "Moriac",
    "Mortlake",
    "Morwell",
    "Mount Beauty",
    "Mount Helen",
    "Mount Macedon",
    "Moyhu",
    "Murchison",
    "Murrayville",
    "Murtoa",
    "Myrtleford",
    "Nagambie",
    "Nar Nar Goon",
    "Nathalia",
    "Natimuk",
    "Neerim South",
    "New Gisborne",
    "Newhaven",
    "Newstead",
    "Nhill",
    "Noorat",
    "Numurkah",
    "Nyah",
    "Nyah West",
    "Nyora",
    "Ocean Grove",
    "Barwon Heads",
    "Officer",
    "Omeo",
    "Orbost",
    "Ouyen",
    "Pakenham",
    "Panton Hill",
    "Paynesville",
    "Pearcedale",
    "Penshurst",
    "Poowong",
    "Porepunkah",
    "Port Albert",
    "Port Campbell",
    "Port Fairy",
    "Port Welshpool",
    "Portarlington",
    "Portland",
    "Pyramid Hill",
    "Quambatook",
    "Queenscliff",
    "Rainbow",
    "Rawson",
    "Red Cliffs",
    "Rhyll",
    "Riddells Creek",
    "Robinvale",
    "Rochester",
    "Rockbank",
    "Romsey",
    "Rosedale",
    "Rupanyup",
    "Rushworth",
    "Rutherglen",
    "Sale",
    "San Remo",
    "Sea Lake",
    "Seaspray",
    "Seville",
    "Seymour",
    "Shepparton",
    "Mooroopna",
    "Shoreham",
    "Skipton",
    "Smythesdale",
    "Snake Valley",
    "Somers",
    "Somerville",
    "St Andrews",
    "St Andrews Beach",
    "St Arnaud",
    "St Leonards",
    "Stanhope",
    "Stawell",
    "Stratford",
    "Strathfieldsaye",
    "Strathmerton",
    "Sunbury",
    "Swan Hill",
    "Swifts Creek",
    "Talbot",
    "Tallangatta",
    "Tallarook",
    "Tangambalanga",
    "Tatura",
    "Tawonga",
    "Terang",
    "Timboon",
    "Tongala",
    "Toora",
    "Tooradin",
    "Torquay",
    "Trafalgar",
    "Traralgon",
    "Trentham",
    "Tungamah",
    "Tyabb",
    "Tyers",
    "Tylden",
    "Tynong",
    "Underbool",
    "Venus Bay",
    "Violet Town",
    "Wallan",
    "Wandong",
    "Heathcote Junction",
    "Wangaratta",
    "Warburton",
    "Warneet East",
    "Warracknabeal",
    "Warragul",
    "Warrnambool",
    "Wedderburn",
    "Whittlesea",
    "Willaura",
    "Winchelsea",
    "Wodonga",
    "Wonga Park",
    "Wonthaggi",
    "Woodend",
    "Woomelang",
    "Woori Yallock",
    "Woorinen",
    "Wycheproof",
    "Yackandandah",
    "Yallourn North",
    "Yarra Glen",
    "Yarra Junction",
    "Yarragon",
    "Yarram",
    "Yarrawonga",
    "Yea",
    "Yinnar",
  ],
  NSW: [
    "Aberdeen",
    "Adaminaby",
    "Adelong",
    "Agnes Banks",
    "Albury",
    "Alstonville",
    "Angourie",
    "Anna Bay",
    "Appin",
    "Ardlethan",
    "Ariah Park",
    "Armidale",
    "Arrawarra",
    "Ashford",
    "Attunga",
    "Austral",
    "Avondale",
    "Awaba",
    "Ballina",
    "Balranald",
    "Bangalow",
    "Baradine",
    "Barellan",
    "Bargo",
    "Barham",
    "Barmedman",
    "Barooga",
    "Barraba",
    "Basin View",
    "Batemans Bay",
    "Bathurst",
    "Batlow",
    "Bawley Point",
    "Beauty Point",
    "Beechwood",
    "Beelbangera",
    "Bega",
    "Bellingen",
    "Bemboka",
    "Bendemeer",
    "Bermagui",
    "Berrara",
    "Berridale",
    "Berrigan",
    "Berrima",
    "Berry",
    "Bilbul",
    "Binalong",
    "Bingara",
    "Binnaway",
    "Blackheath",
    "Blayney",
    "Boat Harbour",
    "Bodalla",
    "Bogangar",
    "Boggabilla",
    "Boggabri",
    "Bombala",
    "Bonalbo",
    "Bonnells Bay",
    "Bonny Hills",
    "Boorowa",
    "Bourke",
    "Bowen Mountain",
    "Bowral",
    "Bowraville",
    "Braidwood",
    "Brandy Hill",
    "Branxton-Greta",
    "Brewarrina",
    "Brightwaters",
    "Broadwater",
    "Broke",
    "Broken Hill",
    "Brooklyn",
    "Brooms Head",
    "Brunswick Heads",
    "Bulahdelah",
    "Bundanoon",
    "Bundarra",
    "Bungendore",
    "Buronga",
    "Burrill Lake",
    "Burringbar",
    "Buxton",
    "Byron Bay",
    "Cabramurra",
    "Callala Bay",
    "Cambewarra",
    "Camden Haven",
    "Camden West",
    "Candelo",
    "Canowindra",
    "Captains Flat",
    "Carcoar",
    "Cargo",
    "Casino",
    "Catherine Hill Bay",
    "Central Coast",
    "Cessnock-Bellbird",
    "Chain Valley Bay",
    "Clarence Town",
    "Clifton Grove",
    "Clunes",
    "Cobar",
    "Cobargo",
    "Cobbitty",
    "Coffs Harbour",
    "Coleambally",
    "Collarenebri",
    "Colo Vale",
    "Condobolin",
    "Coolah",
    "Coolamon",
    "Cooma",
    "Coomba Park",
    "Coomealla",
    "Coonabarabran",
    "Coonamble",
    "Coopernook",
    "Cooranbong",
    "Cootamundra",
    "Copmanhurst",
    "Coraki",
    "Coramba",
    "Corindi Beach",
    "Corlette",
    "Corowa",
    "Couridjah",
    "Coutts Crossing",
    "Cowan",
    "Cowra",
    "Crescent Head",
    "Crookwell",
    "Cudal",
    "Culburra-Orient Point",
    "Culcairn",
    "Cumnock",
    "Cunjurong",
    "Curlewis",
    "Currarong",
    "Dalmeny",
    "Dareton",
    "Darlington Point",
    "Deepwater",
    "Delegate",
    "Delungra",
    "Deniliquin",
    "Denman",
    "Diamond Beach",
    "Dora Creek",
    "Dorrigo",
    "Douglas Park",
    "Dubbo",
    "Dunedoo",
    "Dungog",
    "Dunoon",
    "Durras",
    "East Jindabyne",
    "Eden",
    "Ellalong",
    "Emerald Beach",
    "Emmaville",
    "Erowal Bay",
    "Estella",
    "Eugowra",
    "Euston",
    "Evans Head",
    "Exeter",
    "Fingal Bay",
    "Finley",
    "Fishermans Paradise",
    "Forbes",
    "Forest Hill",
    "Forster-Tuncurry",
    "Frederickton",
    "Freemans Reach",
    "Galston",
    "Ganmain",
    "Gerringong",
    "Gerroa",
    "Geurie",
    "Gilgai",
    "Gilgandra",
    "Gillieston Heights",
    "Glen Innes",
    "Glenorie",
    "Glenreagh",
    "Glossodia",
    "Gloucester",
    "Gol Gol",
    "Goodooga",
    "Goolgowi",
    "Goondiwindi",
    "Goulburn",
    "Grafton",
    "Grasmere",
    "Green Hill",
    "Green Point",
    "Greenwell Point",
    "Grenfell",
    "Gresford",
    "Griffith",
    "Gulargambone",
    "Gulgong",
    "Gulmarrad",
    "Gumly Gumly",
    "Gundagai",
    "Gunnedah",
    "Gunning",
    "Guyra",
    "Gwandalan",
    "Hallidays Point",
    "Hanwood",
    "Harden-Murrumburrah",
    "Harrington",
    "Harwood",
    "Hastings Point",
    "Hat Head",
    "Hawkesbury Heights",
    "Hawks Nest",
    "Hay",
    "Heddon Greta",
    "Helensburgh",
    "Henty",
    "Hill Top",
    "Hillston",
    "Hinton",
    "Holbrook",
    "Howlong",
    "Huskisson",
    "Hyland Park",
    "Iluka",
    "Inverell",
    "Ivanhoe",
    "Jamberoo",
    "Jerilderie",
    "Jindabyne",
    "Jindera",
    "Junction Hill",
    "Junee",
    "Kalaru",
    "Kandos",
    "Kangaroo Valley",
    "Karuah",
    "Katoomba",
    "Kempsey",
    "Kendall",
    "Kenthurst",
    "Khancoban",
    "Kiama",
    "Killingworth",
    "Kings Point",
    "Kitchener",
    "Koorawatha",
    "Kootingal",
    "Korora Bay",
    "Kurmond",
    "Kurrajong",
    "Kurrajong Heights",
    "Kurri Kurri-Weston",
    "Kyogle",
    "Ladysmith",
    "Lake Cargelligo",
    "Lake Cathie",
    "Lake Conjola",
    "Lake Conjola West",
    "Lake Munmorah",
    "Lake Tabourie",
    "Lakewood Estate",
    "Lansdowne",
    "Lawrence",
    "Lawson",
    "Leeton",
    "Lemon Tree Passage",
    "Lennox Head",
    "Lightning Ridge",
    "Lismore",
    "Lithgow",
    "Lochinvar",
    "Lockhart",
    "Londonderry",
    "Long Beach",
    "Luddenham",
    "Lyndhurst",
    "Macksville",
    "Maclean",
    "Maianbar",
    "Maitland",
    "Malua Bay",
    "Manildra",
    "Manilla",
    "Mannering Park",
    "Manning Point",
    "Marulan",
    "Mathoura",
    "McGraths Hill",
    "McMasters Beach",
    "Medlow Bath",
    "Medowie",
    "Menangle",
    "Menangle Park",
    "Mendooran",
    "Menindee",
    "Merimbula",
    "Merriwa",
    "Mid Sapphire Beach",
    "Millfield",
    "Millthorpe",
    "Milton",
    "Minmi",
    "Mirrabooka",
    "Mittagong",
    "Moama",
    "Modanville",
    "Mogo",
    "Molong",
    "Moonbi",
    "Moonee Beach",
    "Mooney Mooney",
    "Moree",
    "Morisset",
    "Moruya",
    "Moruya Heads",
    "Moss Vale",
    "Moulamein",
    "Mount Hunter",
    "Mount Victoria",
    "Mudgee",
    "Mulbring",
    "Mulgoa",
    "Mullumbimby",
    "Mulwala",
    "Mungindi",
    "Murrumbateman",
    "Murrurundi",
    "Murwillumbah",
    "Muswellbrook",
    "Mylestom",
    "Nabiac",
    "Nambucca Heads",
    "Narooma",
    "Narrabri",
    "Narrandera",
    "Narromine",
    "Neath",
    "Nelson Bay",
    "Nemingha",
    "Newcastle",
    "Nimbin",
    "Nimmitabel",
    "Nords Wharf",
    "North Arm Cove",
    "North Richmond",
    "North Rothbury",
    "Nowra",
    "Nundle",
    "Nyngan",
    "Oakdale",
    "Oaklands",
    "Oberon",
    "Ocean Shores",
    "Old Bar",
    "Old Erowal Bay",
    "Orange",
    "Otford",
    "Pacific Palms-Blueys Beach",
    "Pallamallawa",
    "Pambula",
    "Pambula Beach",
    "Parkes",
    "Paterson",
    "Patonga",
    "Paxton",
    "Peak Hill",
    "Perisher Village",
    "Perthville",
    "Picton",
    "Pitt Town",
    "Port Macquarie",
    "Portland",
    "Pottsville Beach",
    "Queanbeyan",
    "Quirindi",
    "Raymond Terrace",
    "Red Rock",
    "Robertson",
    "Rylstone",
    "Safety Beach",
    "Salamander Bay-Soldiers Point",
    "Sandy Beach",
    "Sandy Point",
    "Satur",
    "Sawtell",
    "Scone",
    "Scotts Head",
    "Seaham",
    "Seahampton",
    "Shoalhaven Heads",
    "Silverwater",
    "Singleton",
    "Smiths Lake",
    "Smithtown-Gladstone",
    "South Golden Beach",
    "South West Rocks",
    "Spring Hill",
    "St Georges Basin",
    "Stanwell Park",
    "Stanwell Tops",
    "Stockinbingal",
    "Stroud",
    "Stuarts Point",
    "Suffolk Park",
    "Sunshine",
    "Sussex Inlet",
    "Sydney",
    "Tahmoor",
    "Talbingo",
    "Tamworth",
    "Tapitallee",
    "Taralga",
    "Tarcutta",
    "Taree",
    "Tarraganda",
    "Tathra",
    "Tea Gardens",
    "Temora",
    "Tenterfield",
    "The Oaks",
    "The Rock",
    "Thirlmere",
    "Thredbo Village",
    "Tibooburra",
    "Tingha",
    "Tinonee",
    "Tocumwal",
    "Tomakin",
    "Tomerong",
    "Tooleybuc",
    "Tottenham",
    "Trangie",
    "Trundle",
    "Tucabia",
    "Tullamore",
    "Tumbarumba",
    "Tumbulgum",
    "Tumut",
    "Tura Beach",
    "Tuross Heads",
    "Tweed Heads",
    "Tyalgum",
    "Uki",
    "Ulladulla",
    "Ulmarra",
    "Ungarie",
    "Uralla",
    "Urana",
    "Uranquinty",
    "Urbenville",
    "Urunga",
    "Valla Beach",
    "Vineyard",
    "Wagga Wagga",
    "Wagstaff-Killcare",
    "Wakool",
    "Walcha",
    "Walgett",
    "Walla Walla",
    "Wallabi Point",
    "Wallacia",
    "Wallalong",
    "Wallerawang",
    "Wangi-Rathmines",
    "Wardell",
    "Warialda",
    "Warragamba",
    "Warren",
    "Waterfall",
    "Waterview Heights",
    "Wauchope",
    "Wee Waa",
    "Wellington",
    "Wentworth",
    "Werris Creek",
    "West Hoxton",
    "West Wyalong",
    "White Cliffs",
    "Whitton",
    "Wilberforce",
    "Wilcannia",
    "Willow Vale",
    "Wilton",
    "Windella Downs",
    "Windermere Park",
    "Windsor",
    "Windsor Downs",
    "Wingello",
    "Wingham",
    "Wollongbar",
    "Wollongong",
    "Wolumla",
    "Wongarbon",
    "Woodburn",
    "Woodenbong",
    "Woodstock",
    "Woolgoolga",
    "Wooli",
    "Wooloweyah",
    "Wooroowoolgan",
    "Wyee",
    "Wyee Point",
    "Yamba",
    "Yanco",
    "Yanderra",
    "Yarrawonga Park",
    "Yass",
    "Yellow Rock",
    "Yenda",
    "Yeoval",
    "Yerrinbool",
    "Young",
  ],
  QLD: [
    "Agnes Water",
    "Airlie Beach",
    "Alice River",
    "Alligator Creek",
    "Allingham",
    "Allora",
    "Alpha",
    "Amity",
    "Aramac",
    "Arcadia Bay",
    "Atherton",
    "Augathella",
    "Aurukun",
    "Ayr",
    "Babinda",
    "Bakers Creek",
    "Balgal Beach",
    "Bamaga",
    "Baralaba",
    "Barcaldine",
    "Bargara",
    "Beachmere",
    "Beaudesert",
    "Beerwah",
    "Bell",
    "Biggenden",
    "Biloela",
    "Bingil Bay",
    "Blackall",
    "Blackbutt",
    "Blacks Beach",
    "Blackwater",
    "Bli Bli",
    "Blue Mountain Heights",
    "Bluff",
    "Bohle Plains",
    "Bongaree",
    "Boonah",
    "Boreen Point",
    "Bouldercombe",
    "Boulia",
    "Bowen",
    "Boykambil",
    "Boyne Island",
    "Brandon",
    "Brisbane",
    "Bucasia",
    "Buderim",
    "Bundaberg",
    "Burketown",
    "Burnett Heads",
    "Burpengary",
    "Burrum Heads",
    "Caboolture",
    "Cairns",
    "Cairns Northern Beaches",
    "Calen",
    "Calliope",
    "Caloundra",
    "Cambooya",
    "Camooweal",
    "Campwin Beach",
    "Cannonvale",
    "Canungra",
    "Capella",
    "Caravonica",
    "Cardwell",
    "Cecil Plains",
    "Charleville",
    "Charters Towers",
    "Cherbourg",
    "Childers",
    "Chinchilla",
    "Clermont",
    "Clifton",
    "Cloncurry",
    "Collinsville",
    "Cooktown",
    "Cooloola Cove",
    "Coolum Beach",
    "Coominya",
    "Cooran",
    "Cooroy",
    "Cordalba",
    "Cordelia",
    "Cowal Creek",
    "Craiglie",
    "Crows Nest",
    "Croydon",
    "Cungulla",
    "Cunnamulla",
    "Dajarra",
    "Dalby",
    "Dayboro",
    "Deception Bay",
    "Deeragun",
    "Dimbulah",
    "Dirranbandi",
    "Donnybrook",
    "Doomadgee",
    "Duaringa",
    "Dundowran",
    "Dunwich",
    "Dysart",
    "Eagle Heights",
    "Eidsvold",
    "Eimeo",
    "El Arish",
    "Elliott Heads",
    "Emerald",
    "Emu Park",
    "Esk",
    "Eton",
    "Eumundi",
    "Farleigh",
    "Fernvale",
    "Finch Hatton",
    "Flying Fish Point",
    "Forest Hill",
    "Gatton",
    "Gayndah",
    "Georgetown",
    "Gin Gin",
    "Giru",
    "Gladstone",
    "Glass House Mountains",
    "Glenden",
    "Glenella",
    "Gold Coast",
    "Goombungee",
    "Goomeri",
    "Gordonvale",
    "Gracemere",
    "Grantham",
    "Grasstree Beach",
    "Greenmount",
    "Gympie",
    "Gympie South",
    "Half Tide Beach",
    "Halifax",
    "Hamilton Island",
    "Harrisville",
    "Hector",
    "Helensvale",
    "Helidon",
    "Herberton",
    "Hervey Bay",
    "Highfields",
    "Home Hill",
    "Hope Island",
    "Hope Vale",
    "Horseshoe Bay",
    "Howard",
    "Hughenden",
    "Imbil",
    "Ingham",
    "Inglewood",
    "Injune",
    "Innes Park",
    "Innisfail",
    "Jacobs Well",
    "Jalloonda",
    "Jandowae",
    "Jimboomba",
    "Julia Creek",
    "Kairi",
    "Kalamia Estate",
    "Kalbar",
    "Karalee",
    "Karana Downs",
    "Karumba",
    "Kawana Waters",
    "Kenilworth",
    "Kilcoy",
    "Kilkivan",
    "Killarney",
    "Kingaroy",
    "Kingsthorpe",
    "Kooralbyn",
    "Kowanyama",
    "Kuranda",
    "Kurrimine",
    "Laidley",
    "Landsborough",
    "Lockhart River",
    "Longreach",
    "Lowood",
    "Lucinda",
    "Mackay",
    "Macknade",
    "Malanda",
    "Maleny",
    "Mapleton",
    "Marburg",
    "Marcoola",
    "Marcus Beach",
    "Mareeba",
    "Marian",
    "Maroochydore",
    "Maryborough",
    "Merinda",
    "Middlemount",
    "Miles",
    "Millaa Millaa",
    "Millmerran",
    "Mirani",
    "Miriam Vale",
    "Mission Beach",
    "Mitchell",
    "Monto",
    "Mooloolah",
    "Moore Park",
    "Moranbah",
    "Morayfield",
    "Mossman",
    "Mount Garnet",
    "Mount Isa",
    "Mount Larcom",
    "Mount Low",
    "Mount Morgan",
    "Mount Nebo",
    "Mount Tamborine",
    "Moura",
    "Mourilyan",
    "Mudjimba",
    "Mundubbera",
    "Murgon",
    "Nambour",
    "Nanango",
    "Napranum",
    "Narangba",
    "Nelly Bay",
    "Nerang",
    "New Mapoon",
    "Newell",
    "Ningi",
    "Normanton",
    "North Tamborine",
    "Oakey",
    "Oxenford",
    "Pallarenda",
    "Palm Island",
    "Palmwoods",
    "Peachester",
    "Pentland",
    "Peregian Beach",
    "Picnic Bay",
    "Pittsworth",
    "Planella",
    "Point Lookout",
    "Point Talburpin",
    "Pomona",
    "Pormpuraaw",
    "Port Douglas",
    "Proserpine",
    "Proston",
    "Quilpie",
    "Rainbow Beach",
    "Rathdowney",
    "Ravenshoe",
    "Redland Bay",
    "Richmond",
    "River Heads",
    "Rockhampton",
    "Roma",
    "Rosewood",
    "Rubyvale",
    "Samford",
    "Sandstone Point",
    "Santa Barbara",
    "Sapphire",
    "Sarina",
    "Sarina Beach",
    "Seaforth",
    "Seventeen Seventy",
    "Shoal Point",
    "Silkwood",
    "Smithfield Heights",
    "South Johnstone",
    "South Mission Beach",
    "Springsure",
    "St George",
    "St Pauls",
    "Stanthorpe",
    "Surat",
    "Tambo",
    "Tannum Sands",
    "Tara",
    "Taroom",
    "Taylors Beach",
    "Tewantin-Noosa",
    "Texas",
    "Thangool",
    "Thargomindah",
    "The Junction",
    "The Palms",
    "Theodore",
    "Thursday Island",
    "Tiaro",
    "Tieri",
    "Tin Can Bay",
    "Tolga",
    "Toogoolawah",
    "Toogoom",
    "Toorbul",
    "Toowoomba",
    "Torbanlea",
    "Townsville-Thuringowa",
    "Trebonne",
    "Tully",
    "Tully Heads",
    "Umagico",
    "Victoria Point",
    "Walkerston",
    "Wallangarra",
    "Walloon",
    "Wallumbilla",
    "Wamuran",
    "Wandoan",
    "Wangan",
    "Warwick",
    "Weipa",
    "Willows Gemfields",
    "Winton",
    "Withcott",
    "Wondai",
    "Wonga Beach",
    "Wongaling Beach",
    "Woodford",
    "Woodgate",
    "Woombye",
    "Woorabinda",
    "Woorim",
    "Wujal Wujal",
    "Wyreema",
    "Yandina",
    "Yangan",
    "Yaroomba",
    "Yarrabah",
    "Yarraman",
    "Yelarbon",
    "Yeppoon",
    "Yuleba",
    "Yungaburra",
  ],
  SA: [
    "Adelaide",
    "Aldinga Beach",
    "Andamooka",
    "Angaston",
    "Angle Vale",
    "Ardrossan",
    "Auburn",
    "Balaklava",
    "Balhannah",
    "Barmera",
    "Beachport",
    "Berri",
    "Birdwood",
    "Blanchetown",
    "Blyth",
    "Booleroo Centre",
    "Bordertown",
    "Burra",
    "Bute",
    "Callington",
    "Carrickalinga",
    "Ceduna",
    "Clare",
    "Cleve",
    "Cobdogla",
    "Coffin Bay",
    "Coober Pedy",
    "Coonalpyn",
    "Cowell",
    "Crafers-Bridgewater",
    "Crystal Brook",
    "Cummins",
    "Echunga",
    "Edithburgh",
    "Elliston",
    "Eudunda",
    "Freeling",
    "Gawler",
    "Gladstone",
    "Goolwa",
    "Greenock",
    "Gumeracha",
    "Hahndorf",
    "Hamley Bridge",
    "Hawker",
    "Houghton",
    "Iron Knob",
    "Jamestown",
    "Kadina",
    "Kalangadoo",
    "Kapunda",
    "Karoonda",
    "Keith",
    "Kersbrook",
    "Kimba",
    "Kingscote",
    "Kingston Se",
    "Lameroo",
    "Laura",
    "Leigh Creek",
    "Lobethal",
    "Loxton",
    "Lucindale",
    "Lyndoch",
    "Macclesfield",
    "Maitland",
    "Mallala",
    "Mannum",
    "Maslin Beach",
    "McLaren Vale",
    "Meadows",
    "Meningie",
    "Middleton",
    "Milang",
    "Millicent",
    "Minlaton",
    "Mintabie",
    "Moonta",
    "Moorook",
    "Morgan",
    "Mount Barker",
    "Mount Burr",
    "Mount Compass",
    "Mount Gambier",
    "Mount Pleasant",
    "Mount Torrens",
    "Murray Bridge",
    "Nairne",
    "Nangwarry",
    "Napperby",
    "Naracoorte",
    "Normanville",
    "Nuriootpa",
    "Oakbank",
    "Orroroo",
    "Owen",
    "Paringa",
    "Penola",
    "Peterborough",
    "Pinnaroo",
    "Port Augusta",
    "Port Broughton",
    "Port Elliot",
    "Port Germein",
    "Port Lincoln",
    "Port MacDonnell",
    "Port Neill",
    "Port Pirie",
    "Port Victoria",
    "Port Vincent",
    "Port Wakefield",
    "Quorn",
    "Renmark",
    "Riverton",
    "Robe",
    "Roseworthy",
    "Roxby Downs",
    "Saddleworth",
    "Sellicks Beach",
    "Snowtown",
    "Spalding",
    "Springton",
    "Stansbury",
    "Strathalbyn",
    "Streaky Bay",
    "Summertown",
    "Swan Reach",
    "Tailem Bend",
    "Tantanoola",
    "Tanunda",
    "Tarpeena",
    "Tintinara",
    "Tumby Bay",
    "Two Wells",
    "Uraidla",
    "Victor Harbor",
    "Virginia",
    "Waikerie",
    "Wallaroo",
    "Warooka",
    "Wasleys",
    "Whyalla",
    "Williamstown",
    "Willunga",
    "Wilmington",
    "Wirrabara",
    "Woodside",
    "Woomera",
    "Wudinna",
    "Yalata",
    "Yankalilla",
    "Yorketown",
  ],
  WA: [
    "Albany",
    "Allanson",
    "Augusta",
    "Australind",
    "Bardi (One Arm Point)",
    "Beagle Bay",
    "Beverley",
    "Binningup",
    "Boddington",
    "Boyanup",
    "Boyup Brook",
    "Bremer Bay",
    "Bridgetown",
    "Brookton",
    "Broome",
    "Bruce Rock",
    "Brunswick Junction",
    "Bunbury",
    "Burekup",
    "Busselton",
    "Byford",
    "Capel",
    "Carnamah",
    "Carnarvon",
    "Cervantes",
    "Chidlow",
    "Collie",
    "Coolgardie",
    "Coral Bay",
    "Corrigin",
    "Cranbrook",
    "Cuballing",
    "Cue",
    "Cunderdin",
    "Dalwallinu",
    "Dampier",
    "Dardanup",
    "Darkan",
    "Denham",
    "Denmark",
    "Derby",
    "Dongara",
    "Donnybrook",
    "Dowerin",
    "Drummond Cove",
    "Dumbleyung",
    "Dunsborough",
    "Dwellingup",
    "East Bullsbrook",
    "Eaton",
    "Eneabba",
    "Esperance",
    "Exmouth",
    "Fitzroy Crossing",
    "Furnissdale",
    "Gelorup",
    "Geraldton",
    "Gingin",
    "Gnowangerup",
    "Golden Bay-Singleton",
    "Goomalling",
    "Green Head",
    "Greenbushes",
    "Halls Creek",
    "Harvey",
    "Hopetoun",
    "Jarrahdale",
    "Jerramungup",
    "Jurien Bay",
    "Kalbarri",
    "Kalgoorlie-Boulder",
    "Kalumburu Aboriginal Community",
    "Kambalda",
    "Karratha",
    "Katanning",
    "Kellerberrin",
    "Kojonup",
    "Kondinin",
    "Koorda",
    "Kulin",
    "Kununurra",
    "Kwinana",
    "Lagrange Aboriginal Community",
    "Lake Grace",
    "Lancelin",
    "Laverton",
    "Leeman",
    "Leinster",
    "Leonora",
    "Leschenault",
    "Little Grove",
    "Looma Aboriginal Community",
    "Mahogany Creek",
    "Mandurah",
    "Manjimup",
    "Marble Bar",
    "Margaret River",
    "Marvel Loch",
    "Meekatharra",
    "Merredin",
    "Mingenew",
    "Moora",
    "Morawa",
    "Mount Barker",
    "Mount Helena",
    "Mount Magnet",
    "Mukinbudin",
    "Mullewa",
    "Mundaring",
    "Mundijong",
    "Mungullah",
    "Nannup",
    "Narembeen",
    "Narrogin",
    "Newman",
    "Norseman",
    "North Pinjarra",
    "Northam",
    "Northampton",
    "Northcliffe",
    "Onslow",
    "Oombulgurri",
    "Pannawonica",
    "Paraburdoo",
    "Parkerville",
    "Pemberton",
    "Peppermint Grove",
    "Perth",
    "Pingelly",
    "Pinjarra",
    "Point Samson",
    "Port Hedland",
    "Quairading",
    "Quindalup",
    "Ravensthorpe",
    "Rockingham",
    "Roebourne",
    "Rottnest Island",
    "Sawyers Valley",
    "Serpentine",
    "Southern Cross",
    "Stoneville",
    "Stratham",
    "Tambellup",
    "Tammin",
    "Three Springs",
    "Tom Price",
    "Toodyay",
    "Turkey Creek",
    "Two Rocks",
    "Wagin",
    "Walpole",
    "Warburton",
    "Waroona",
    "Wickepin",
    "Wickham",
    "Williams",
    "Wiluna",
    "Wongan Hills",
    "Wooroloo",
    "Wundowie",
    "Wyalkatchem",
    "Wyndham",
    "Yanchep",
    "Yarloop",
    "York",
    "Yunderup",
  ],
  TAS: [
    "Bagdad",
    "Beaconsfield",
    "Beauty Point",
    "Bicheno",
    "Bothwell",
    "Bracknell",
    "Branxholm",
    "Bridgewater",
    "Bridport",
    "Burnie",
    "Campania",
    "Campbell Town",
    "Carrick",
    "Collinsvale",
    "Cremorne",
    "Cressy",
    "Currie",
    "Cygnet",
    "Deloraine",
    "Devonport",
    "Dilston",
    "Dodges Ferry",
    "Dover",
    "Dunalley",
    "Eaglehawk Neck",
    "Evandale",
    "Exeter",
    "Fern Tree",
    "Fingal",
    "Forth",
    "Franklin",
    "Gawler",
    "Geeveston",
    "George Town",
    "Gravelly Beach",
    "Hadspen",
    "Heybridge",
    "Hobart",
    "Howden",
    "Huonville",
    "Kempton",
    "Kettering",
    "Kingston",
    "Lanena",
    "Latrobe",
    "Lauderdale",
    "Launceston",
    "Legana",
    "Lewisham",
    "Lilydale",
    "Longford",
    "Low Head",
    "Margate",
    "Maydena",
    "Mole Creek",
    "New Norfolk",
    "Nubeena",
    "Oatlands",
    "Old Beach",
    "Opossum Bay",
    "Orford",
    "Otago",
    "Penguin",
    "Perth",
    "Pontville",
    "Port Sorell",
    "Primrose Sands",
    "Queenstown",
    "Railton",
    "Richmond",
    "Ridgley",
    "Ringarooma",
    "Rosebery",
    "Ross",
    "Scamander",
    "Scottsdale",
    "Seven Mile Beach",
    "Sheffield",
    "Sisters Beach",
    "Smithton",
    "Snug",
    "Sorell",
    "South Arm",
    "St Helens",
    "St Marys",
    "Stanley",
    "Strahan",
    "Sulphur Creek",
    "Swansea",
    "Triabunna",
    "Tullah",
    "Turners Beach",
    "Ulverstone",
    "Waratah",
    "Westbury",
    "White Beach",
    "Woodbridge",
    "Wynyard",
    "Zeehan",
  ],
  NT: [
    "Adelaide River",
    "Ali-Curung",
    "Alice Springs",
    "Alpurrurulam",
    "Alyangula",
    "Ampilatwatja",
    "Angurugu",
    "Barunga (Bamyili)",
    "Batchelor",
    "Belyuen",
    "Borroloola",
    "Coonawarra",
    "Daly River",
    "Darwin",
    "Elliott",
    "Galiwinku",
    "Gapuwiyak",
    "Gunyangara",
    "Hermannsburg",
    "Howard Springs",
    "Humpty Doo-McMinns Lagoon",
    "Jabiru",
    "Kalkarinji (Wave Hill)",
    "Kaltukatjara (Docker River)",
    "Katherine",
    "Kintore",
    "Lajamanu",
    "Maningrida",
    "Mataranka",
    "Milikapiti (Snake Bay)",
    "Milingimbi",
    "Minjilang",
    "Nguiu",
    "Ngukurr",
    "Nhulunbuy",
    "Numbulwar",
    "Oenpelli",
    "Palmerston",
    "Papunya Aboriginal Community",
    "Pine Creek",
    "Pirlangimpi (Garden Point)",
    "Port Keats (Wadeye)",
    "Ramingining",
    "Santa Teresa",
    "Tennant Creek",
    "Timber Creek",
    "Umbakumba",
    "Virginia-Bees Creek",
    "Warruwi",
    "Yirrkala",
    "Yuendumu",
    "Yulara Tourist Village",
  ],
  ACT: [
    "Canberra",
    "Hall",
  ],
};

export default function SurveyForm() {
  const [formData, setFormData] = useState({
    givenName: '',
    surname: '',
    contactNumber: '',
    email: '',
    farmName: '',
    farmStreetAddress: '',
    townCity: '',
    postcode: '',
    state: '',
    region: ''
  });
  const [submitMessage, setSubmitMessage] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const availableRegions = REGIONS_BY_STATE[formData.state] ?? [];

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>,
  ) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleStateChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const nextState = e.target.value;
    if (nextState === "__clear__") {
      setFormData((prev) => ({ ...prev, state: "", region: "" }));
      return;
    }

    setFormData((prev) => ({
      ...prev,
      state: nextState,
      // Clear region when state changes.
      region: prev.state === nextState ? prev.region : "",
    }));
  };

  const handleRegionChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const nextRegion = e.target.value;
    setFormData((prev) => ({
      ...prev,
      region: nextRegion === "__clear__" ? "" : nextRegion,
    }));
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsSubmitting(true);
    setSubmitMessage('');

    try {
      const response = await fetch('/api/survey/submit', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
      const result = await response.json();
      if (!response.ok) {
        throw new Error(result.error ?? 'Failed to submit survey.');
      }
      setSubmitMessage(`Submitted successfully. Response ID: ${result.responseId}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      setSubmitMessage(`Submit failed: ${message}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-white font-sans text-gray-800">
      {/* Header */}
      <header className="bg-[#091a40] h-28 flex items-center px-8 sm:px-16">
        <img
          src="https://q.surveys.unimelb.edu.au/CP/Graphic.php?IM=IM_6PTif2kLNeUE5Bs"
          alt="The University of Melbourne"
          className="h-16"
          /* Note: You will need to add a white logo to your public folder */
        />
      </header>

      {/* Progress Bar */}
      <div className="w-full bg-gray-300 h-[6px]">
        <div className="bg-[#091a40] h-full w-[1%]"></div>
      </div>
      <div className="px-4 py-1 text-sm text-gray-600">
        0% Survey Completion
      </div>

      {/* Form Container */}
      <main className="max-w-3xl mx-auto py-12 px-6 sm:px-12">
        <form onSubmit={handleSubmit} className="space-y-6">

          <h2 className="text-xl text-gray-800 mb-6">
            <span className="text-black">*</span> Please provide the following information.
          </h2>

          <div className="space-y-5">
            <div className="flex flex-col">
              <label className="mb-1 text-sm text-gray-700">Contact given name</label>
              <input
                type="text" name="givenName" value={formData.givenName} onChange={handleChange}
                className="border border-gray-300 rounded-[4px] p-2.5 bg-[#f8f9fa] focus:outline-none focus:border-[#091a40]"
              />
            </div>

            <div className="flex flex-col">
              <label className="mb-1 text-sm text-gray-700">Contact surname</label>
              <input
                type="text" name="surname" value={formData.surname} onChange={handleChange}
                className="border border-gray-300 rounded-[4px] p-2.5 bg-[#f8f9fa] focus:outline-none focus:border-[#091a40]"
              />
            </div>

            <div className="flex flex-col">
              <label className="mb-1 text-sm text-gray-700">Contact number</label>
              <input
                type="tel" name="contactNumber" value={formData.contactNumber} onChange={handleChange}
                className="border border-gray-300 rounded-[4px] p-2.5 bg-[#f8f9fa] focus:outline-none focus:border-[#091a40]"
              />
            </div>

            <div className="flex flex-col">
              <label className="mb-1 text-sm text-gray-700">Email</label>
              <input
                type="email" name="email" value={formData.email} onChange={handleChange}
                className="border border-gray-300 rounded-[4px] p-2.5 bg-[#f8f9fa] focus:outline-none focus:border-[#091a40]"
              />
            </div>

            <div className="flex flex-col">
              <label className="mb-1 text-sm text-gray-700">Farm name</label>
              <input
                type="text" name="farmName" value={formData.farmName} onChange={handleChange}
                className="border border-gray-300 rounded-[4px] p-2.5 bg-[#f8f9fa] focus:outline-none focus:border-[#091a40]"
              />
            </div>

            <div className="flex flex-col">
              <label className="mb-1 text-sm text-gray-700">Farm street address</label>
              <input
                type="text" name="farmStreetAddress" value={formData.farmStreetAddress} onChange={handleChange}
                className="border border-gray-300 rounded-[4px] p-2.5 bg-[#f8f9fa] focus:outline-none focus:border-[#091a40]"
              />
            </div>

            <div className="flex flex-col">
              <label className="mb-1 text-sm text-gray-700">Town/City</label>
              <input
                type="text" name="townCity" value={formData.townCity} onChange={handleChange}
                className="border border-gray-300 rounded-[4px] p-2.5 bg-[#f8f9fa] focus:outline-none focus:border-[#091a40]"
              />
            </div>

            <div className="flex flex-col">
              <label className="mb-1 text-sm text-gray-700">Postcode</label>
              <input
                type="text" name="postcode" value={formData.postcode} onChange={handleChange}
                className="border border-gray-300 rounded-[4px] p-2.5 bg-[#f8f9fa] focus:outline-none focus:border-[#091a40]"
              />
            </div>
          </div>

          <div className="pt-8">
            <h2 className="text-lg text-gray-800 mb-4">
              <span className="text-black">*</span> State and region (If you do not know which region your farm is located in, please search the region based on your nearest town <a href="#" className="underline text-blue-700">here</a>)
            </h2>

            <div className="space-y-5">
              <div className="flex flex-col">
                <label className="mb-1 text-sm text-gray-700">State</label>
                <select
                  name="state" value={formData.state} onChange={handleStateChange}
                  className="border border-gray-300 rounded-[4px] p-2.5 bg-[#f8f9fa] focus:outline-none focus:border-[#091a40] appearance-none"
                >
                  <option value=""></option>
                  {formData.state ? <option value="__clear__">Clear selection</option> : null}
                  <option value="VIC">Victoria</option>
                  <option value="NSW">New South Wales</option>
                  <option value="QLD">Queensland</option>
                  <option value="WA">Western Australia</option>
                  <option value="SA">South Australia</option>
                  <option value="TAS">Tasmania</option>
                  <option value="ACT">Australian Capital Territory</option>
                  <option value="NT">Northern Territory</option>
                </select>
              </div>

              <div className="flex flex-col">
                <label className="mb-1 text-sm text-gray-700">Region</label>
                <select
                  name="region" value={formData.region} onChange={handleRegionChange}
                  disabled={!formData.state || availableRegions.length === 0}
                  className="border border-gray-300 rounded-[4px] p-2.5 bg-[#f8f9fa] focus:outline-none focus:border-[#091a40] appearance-none"
                >
                  {!formData.state ? (
                    <option value="">Please select state first</option>
                  ) : availableRegions.length === 0 ? (
                    <option value="">No regions configured for this state</option>
                  ) : (
                    <>
                      <option value=""></option>
                      {formData.region ? (
                        <option value="__clear__">Clear selection</option>
                      ) : null}
                      {availableRegions.map((region) => (
                        <option key={region} value={region}>
                          {region}
                        </option>
                      ))}
                    </>
                  )}
                </select>
              </div>
            </div>
          </div>

          {/* Submit/Next Button */}
          <div className="flex justify-end pt-8">
            <button
              type="submit"
              disabled={isSubmitting}
              className="bg-[#091a40] text-white px-6 py-2.5 rounded hover:bg-[#071433] transition-colors flex items-center font-medium"
            >
              {isSubmitting ? 'Submitting...' : (
                <>
                  Next page <span className="ml-2 font-bold">&gt;</span>
                </>
              )}
            </button>
          </div>
          {submitMessage ? (
            <p className="text-sm text-gray-700">{submitMessage}</p>
          ) : null}
        </form>
      </main>
    </div>
  );
}